---
- hosts: app
  remote_user: "{{ users.system.name }}"
  become: yes
  vars_files:
    - ../vars/user-mapping.yml
    - "{{ env_file }}"
  roles:
    - { role: lvm, lvm_dev: "{{ env.disk1 }}", lvm_path: '/application-logs' }
    - { role: swap }
    - { role: sys-monitoring }
    - { role: python }
    - { role: docker }
    - { role: docker-registry }
