---
- hosts: build
  remote_user: "{{ users.system.name }}"
  become: yes
  vars_files:
    - ../vars/secret.yml
    - ../vars/user-mapping.yml
    - "{{ env_file }}"
  roles:
    - { role: lvm, lvm_dev: "{{ env.disk1 }}", lvm_path: '/application-logs' }
    - { role: lvm, lvm_dev: "{{ env.disk2 }}", lvm_path: '/container-registry' }
    - { role: lvm, lvm_dev: "{{ env.disk3 }}", lvm_path: '/git-repositories' }
    - { role: swap }
    - { role: sys-monitoring }
    - { role: python }
    - { role: ansible }
    - { role: docker }
    - { role: docker-registry, tasks: configure-registry-connection }
    - { role: docker-registry, tasks: create-registry }
    - { role: gitlab }
