---
- hosts: service-discovery
  remote_user: "{{ users.system.name }}"
  become: yes
  gather_facts: true
  vars_files:
    - ../vars/user-mapping.yml
    - "{{ env_file }}"
  roles:
    - { role: swap }
    - { role: sys-monitoring }
    - { role: python }
    - { role: consul, tasks: consul-server }
    - { role: consul, tasks: consul-gui }
