---
- hosts: app
  remote_user: senpai
  become: yes
  vars_files:
    - vars/env.vagrant.yml
#    - vars/env.digital_ocean.yml
#    - vars/secret.yml
    - vars/user-mapping.yml
  roles:
    - { role: lvm, lvm_dev: "{{ env.disk1 }}", lvm_path: '/application-logs' }
    - { role: swap }
    - { role: sys-monitoring }
    - { role: python }
    - { role: docker }
    - { role: docker-registry }