---
- hosts: build
  remote_user: senpai
  become: yes
  vars_files:
    - vars/secret.yml
    - vars/user-mapping.yml
  roles:
    - { role: lvm, lvm_dev: '/dev/sdd', lvm_path: '/application-logs' }
    - { role: lvm, lvm_dev: '/dev/sdb', lvm_path: '/container-registry' }
    - { role: lvm, lvm_dev: '/dev/sdc', lvm_path: '/git-repositories' }
    - { role: swap }
    - { role: sys-monitoring }
    - { role: python }
    - { role: ansible }
    - { role: docker }
    - { role: docker-registry, tasks: configure-registry-connection }
    - { role: docker-registry, tasks: create-registry }
    - { role: gitlab }